[package]
name = "auto_piano_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.2"
mki = "0.2.3"
serde = "1.0.178"
serde_json = "1.0.104"

[build-dependencies]
winres = "0.1.12"
